/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massalud.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import massalud.controlador.AfiliadoData;
import massalud.controlador.Conexion;
import massalud.controlador.EspecialidadData;
import massalud.controlador.PrestadorData;
import massalud.modelo.Afiliado;

/**
 *
 * @author tetid
 */
public class VistaAdministrarAfiliado extends javax.swing.JInternalFrame {
    
    private Conexion conexion;
    private AfiliadoData ad;
    
    /**
     * Creates new form VistaAdministrarAfiliado
     */
    public VistaAdministrarAfiliado() {
        initComponents();
        
        try {
            conexion = new Conexion();
            ad = new AfiliadoData(conexion);
 
        } catch (ClassNotFoundException ex) {
            System.out.println("No se pudo crear el AfiliadoData");
            Logger.getLogger(VistaAdministrarPrestador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tDniAfiliado = new javax.swing.JTextField();
        cbActivo = new javax.swing.JCheckBox();
        btCrear = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btDesactivar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tIdAfiliado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNombreAfiliado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tApellidoAfiliado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btBuscarPorDni = new javax.swing.JButton();
        btSalir1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Administrar Afiliado");

        tDniAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDniAfiliadoActionPerformed(evt);
            }
        });
        tDniAfiliado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tDniAfiliadoKeyTyped(evt);
            }
        });

        cbActivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbActivo.setText("Activo");

        btCrear.setText("Crear");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btDesactivar.setText("Desactivar/activar");
        btDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesactivarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar por id");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id Afiliado:");

        tIdAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdAfiliadoActionPerformed(evt);
            }
        });
        tIdAfiliado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tIdAfiliadoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        tNombreAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreAfiliadoActionPerformed(evt);
            }
        });
        tNombreAfiliado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombreAfiliadoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");

        tApellidoAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApellidoAfiliadoActionPerformed(evt);
            }
        });
        tApellidoAfiliado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tApellidoAfiliadoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DNI:");

        btBuscarPorDni.setText("Buscar por DNI");
        btBuscarPorDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPorDniActionPerformed(evt);
            }
        });

        btSalir1.setText("Salir");
        btSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(336, 336, 336))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(336, 336, 336))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addGap(165, 165, 165)
                        .addComponent(btBuscar)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tIdAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(tNombreAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tApellidoAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbActivo)
                                        .addComponent(tDniAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscarPorDni)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btCrear)
                .addGap(45, 45, 45)
                .addComponent(btActualizar)
                .addGap(61, 61, 61)
                .addComponent(btDesactivar)
                .addGap(39, 39, 39)
                .addComponent(btLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIdAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombreAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tApellidoAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDniAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPorDni))
                .addGap(18, 18, 18)
                .addComponent(cbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCrear)
                    .addComponent(btActualizar)
                    .addComponent(btDesactivar)
                    .addComponent(btLimpiar))
                .addGap(29, 29, 29)
                .addComponent(btSalir1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDniAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDniAfiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDniAfiliadoActionPerformed

    private void tDniAfiliadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDniAfiliadoKeyTyped
        char myChar = evt.getKeyChar();

        if(!Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tDniAfiliadoKeyTyped

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed

        int idAfiliado;
        String nombre;
        String apellido;
        int dni;
        boolean activo;
        

        Afiliado a;

        nombre = tNombreAfiliado.getText();
        apellido = tApellidoAfiliado.getText();
        dni = Integer.parseInt(tDniAfiliado.getText());
        activo = cbActivo.isSelected();

        a = new Afiliado(nombre, apellido, dni, activo);
        ad.agregarAfiliado(a);

        tIdAfiliado.setText(a.getIdAfiliado() + "");
    }//GEN-LAST:event_btCrearActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        int idAfiliado;
        String nombre;
        String apellido;
        int dni;
        boolean activo;        

        Afiliado a;

        if(tIdAfiliado.getText() != null && tNombreAfiliado.getText() != null && tApellidoAfiliado.getText() != null && tDniAfiliado.getText() != null && (tDniAfiliado.getText().length() >= 7 && tDniAfiliado.getText().length() <= 8)){
            idAfiliado = Integer.parseInt(tIdAfiliado.getText());
            nombre = tNombreAfiliado.getText();
            apellido = tApellidoAfiliado.getText();
            dni = Integer.parseInt(tDniAfiliado.getText());
            activo = cbActivo.isSelected();

            a = new Afiliado(nombre, apellido, dni, activo);
            a.setIdAfiliado(idAfiliado);

            ad.actualizarAfiliado(a);
        }
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesactivarActionPerformed
        int idAfiliado;
        Afiliado a;

        if(tIdAfiliado.getText() != null){
            idAfiliado = Integer.parseInt(tIdAfiliado.getText());
            a = ad.buscarAfiliado(idAfiliado);

            if(a.isActivo()){
                cbActivo.setSelected(false);
                a.setActivo(false);
            }else{
                cbActivo.setSelected(true);
                a.setActivo(true);
            }

            ad.actualizarEstadoAfiliado(a);

        }
    }//GEN-LAST:event_btDesactivarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        tIdAfiliado.setText("");
        tNombreAfiliado.setText("");
        tApellidoAfiliado.setText("");
        tDniAfiliado.setText("");
        cbActivo.setSelected(false);
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        int idAfiliado;
        String nombre;
        String apellido;
        int dni;
        boolean activo;
        

        Afiliado a;
        idAfiliado = Integer.parseInt(tIdAfiliado.getText());
        a = ad.buscarAfiliado(idAfiliado);

        nombre = a.getNombre();
        apellido = a.getApellido();
        dni = a.getDni();
        activo = a.isActivo();
        

        tNombreAfiliado.setText(nombre);
        tApellidoAfiliado.setText(apellido);
        tDniAfiliado.setText(dni + "");
        cbActivo.setSelected(activo);

    }//GEN-LAST:event_btBuscarActionPerformed

    private void tIdAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdAfiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdAfiliadoActionPerformed

    private void tIdAfiliadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdAfiliadoKeyTyped
        char myChar = evt.getKeyChar();

        if(!Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tIdAfiliadoKeyTyped

    private void tNombreAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreAfiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreAfiliadoActionPerformed

    private void tNombreAfiliadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreAfiliadoKeyTyped
        char myChar = evt.getKeyChar();

        if(Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tNombreAfiliadoKeyTyped

    private void tApellidoAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidoAfiliadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApellidoAfiliadoActionPerformed

    private void tApellidoAfiliadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tApellidoAfiliadoKeyTyped
        char myChar = evt.getKeyChar();

        if(Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tApellidoAfiliadoKeyTyped

    private void btBuscarPorDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPorDniActionPerformed
        int idAfiliado;
        String nombre;
        String apellido;
        int dni;
        boolean activo;
        

        Afiliado a;
        if(tDniAfiliado.getText() != null){
            dni = Integer.parseInt(tDniAfiliado.getText());
            a = ad.buscarAfiliadoPorDni(dni);


            idAfiliado = a.getIdAfiliado();
            nombre = a.getNombre();
            apellido = a.getApellido();
            dni = a.getDni();
            activo = a.isActivo();

            tIdAfiliado.setText(idAfiliado + "");
            tNombreAfiliado.setText(nombre);
            tApellidoAfiliado.setText(apellido);
            tDniAfiliado.setText(dni + "");
            cbActivo.setSelected(activo);
        }
        
    }//GEN-LAST:event_btBuscarPorDniActionPerformed

    private void btSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_btSalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscarPorDni;
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btDesactivar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btSalir1;
    private javax.swing.JCheckBox cbActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tApellidoAfiliado;
    private javax.swing.JTextField tDniAfiliado;
    private javax.swing.JTextField tIdAfiliado;
    private javax.swing.JTextField tNombreAfiliado;
    // End of variables declaration//GEN-END:variables
}
