/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massalud.vista;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import massalud.controlador.AfiliadoData;
import massalud.controlador.Conexion;
import massalud.controlador.OrdenData;
import massalud.modelo.Orden;

/**
 *
 * @author tetid
 */
public class VistaListarOrdenesPorFecha extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private OrdenData od;
    private AfiliadoData ad;
    private List<Orden> listaOrdenes;
    private Conexion conexion;
    
    /**
     * Creates new form VistaListarOrdenesPorFecha
     */
    public VistaListarOrdenesPorFecha() {
        initComponents();
        
        try {
            conexion = new Conexion();
//            connection = conexion.getConexion();


            modelo = new DefaultTableModel();        
            
            od = new OrdenData(conexion);            
            ad = new AfiliadoData(conexion);
            
            dcFecha.getDateEditor().setEnabled(false);
            
            listaOrdenes = od.listarOrdenes();
            
            
            armarCabeceraTabla();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaListarAfiliados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btSalir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOrdenes = new javax.swing.JTable();
        dcFecha = new com.toedter.calendar.JDateChooser();
        btAnular = new javax.swing.JButton();

        jLabel1.setText("Lista de Ordenes por Fecha");

        btSalir1.setText("Salir");
        btSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese la Fecha:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        tOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tOrdenes);

        btAnular.setText("Anular/Activar");
        btAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btAnular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalir1)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalir1)
                    .addComponent(btAnular))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_btSalir1ActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
//        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
//        String fechaIngresada = formato.format(dcFecha.getDate());
//        
//        LocalDate fecha = LocalDate.parse(fechaIngresada, DateTimeFormatter.ofPattern("dd-MM-yyyy"));

        cargarDatos();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnularActionPerformed
        int idOrdenSeleccionada;
        int filaSeleccionada;

        Orden o;

        if(tOrdenes.getSelectedRow() != -1){
            filaSeleccionada = tOrdenes.getSelectedRow();
            idOrdenSeleccionada = (int)modelo.getValueAt(filaSeleccionada, 0);

            o = od.buscarOrden(idOrdenSeleccionada);

            if(o.isActivo()){
                o.setActivo(false);
            }else{
                o.setActivo(true);
            }

            od.actualizarEstadoOrden(o);

            listaOrdenes = od.listarOrdenes();
            cargarDatos();
        }

    }//GEN-LAST:event_btAnularActionPerformed

    
    public void armarCabeceraTabla(){
        List<Object> columnas = new ArrayList<Object>();
        
        columnas.add("Id Orden");
        columnas.add("Fecha");
        columnas.add("Forma de Pago");
        columnas.add("Importe");
        columnas.add("Nombre Prestador");
        columnas.add("Apellido Prestador");
        columnas.add("Dni Afiliado");
        columnas.add("Dia del Turno");
        columnas.add("Hora");
        columnas.add("Activo");

        
        for(Object columna : columnas){
            modelo.addColumn(columna);
        }
        
        tOrdenes.setModel(modelo);
    }
    
    public void borrarFilasTabla(){
        int nFilas = modelo.getRowCount() - 1;
        
        for(int i = nFilas; i >= 0; i--){
            modelo.removeRow(i);
        }
        
    }
    
    public void cargarDatos(){
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        String fechaIngresada = formato.format(dcFecha.getDate());
        
        LocalDate fecha = LocalDate.parse(fechaIngresada, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        
        borrarFilasTabla();
        
                
        for(Orden o : listaOrdenes){
            
            if(o.getFecha().isEqual(fecha)){
                modelo.addRow(new Object[]{o.getIdOrden(), o.getFecha(),
                    o.getFormaPago(), o.getImporte(),o.getIdHorario().getIdPrestador().getNombre(),
                    o.getIdHorario().getIdPrestador().getApellido(), o.getIdAfiliado().getDni(),
                    o.getIdHorario().getDia(), o.getIdHorario().getHorarioAtencion(), o.isActivo()});
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnular;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btSalir1;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tOrdenes;
    // End of variables declaration//GEN-END:variables
}
