/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massalud.vista;

import massalud.modelo.Especialidad;

/**
 *
 * @author tetid
 */
public class VistaAdministrarPrestador extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAdministrarPrestador
     */
    public VistaAdministrarPrestador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tIdEspecialidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNombreEspecialidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tNombreEspecialidad1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tNombreEspecialidad2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        cbActivo = new javax.swing.JCheckBox();
        btGuardar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Administrar Prestador");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id Prestador:");

        tIdEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdEspecialidadActionPerformed(evt);
            }
        });
        tIdEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tIdEspecialidadKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        tNombreEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreEspecialidadActionPerformed(evt);
            }
        });
        tNombreEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombreEspecialidadKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");

        tNombreEspecialidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreEspecialidad1ActionPerformed(evt);
            }
        });
        tNombreEspecialidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombreEspecialidad1KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DNI:");

        tNombreEspecialidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreEspecialidad2ActionPerformed(evt);
            }
        });
        tNombreEspecialidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombreEspecialidad2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Especialidad:");

        cbActivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbActivo.setText("Activo");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btBorrar.setText("Desactivar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tNombreEspecialidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tNombreEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tIdEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tNombreEspecialidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbActivo)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btActualizar)
                                        .addGap(114, 114, 114)))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBorrar)
                                .addGap(45, 45, 45)))
                        .addComponent(btLimpiar)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIdEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombreEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombreEspecialidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombreEspecialidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btActualizar)
                    .addComponent(btBorrar)
                    .addComponent(btLimpiar))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        int idEspecialidad;
        String nombre;

        int maximo = listaEspecialidades.size();

        Especialidad e;

        if((tIdEspecialidad.getText() != null && !tIdEspecialidad.getText().isEmpty())){
            idEspecialidad = Integer.parseInt(tIdEspecialidad.getText());
            if(idEspecialidad <= maximo){
                e = ed.buscarEspecialidad(idEspecialidad);

                nombre = e.getEspecialidad();

                tNombreEspecialidad.setText(nombre);
            }else{
                JOptionPane.showMessageDialog(this, "No se encuentra en la base de datos");
            }

        }else{
            JOptionPane.showMessageDialog(this, "Por favor ingrese un id de especialidad");
        }

    }//GEN-LAST:event_btBuscarActionPerformed

    private void tIdEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdEspecialidadActionPerformed

    private void tIdEspecialidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdEspecialidadKeyTyped
        char myChar = evt.getKeyChar();

        if(!Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tIdEspecialidadKeyTyped

    private void tNombreEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreEspecialidadActionPerformed

    private void tNombreEspecialidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreEspecialidadKeyTyped
        char myChar = evt.getKeyChar();

        if(Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tNombreEspecialidadKeyTyped

    private void tNombreEspecialidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreEspecialidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreEspecialidad1ActionPerformed

    private void tNombreEspecialidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreEspecialidad1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreEspecialidad1KeyTyped

    private void tNombreEspecialidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreEspecialidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreEspecialidad2ActionPerformed

    private void tNombreEspecialidad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreEspecialidad2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreEspecialidad2KeyTyped

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed

        String nombre;
        LocalDate fecNac;
        boolean activo;

        Alumno a;

        nombre = tNombreAlumno.getText();
        fecNac = LocalDate.parse(tFecNacAlumno.getText());
        activo = cbActivo.isSelected();

        a = new Alumno(nombre, fecNac, activo);
        ad.guardarAlumno(a);
        tIdAlumno.setText(a.getId() + "");
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        int idAlumno;
        String nombre;
        LocalDate fecNac;
        boolean activo;

        Alumno a;

        if(tIdAlumno.getText() != null){
            idAlumno = Integer.parseInt(tIdAlumno.getText());
            nombre = tNombreAlumno.getText();
            fecNac = LocalDate.parse(tFecNacAlumno.getText());
            activo = cbActivo.isSelected();

            a = new Alumno(nombre, fecNac, activo);
            a.setId(idAlumno);

            ad.actualizarAlumno(a);
        }

    }//GEN-LAST:event_btActualizarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        int idAlumno;
        if(tIdAlumno.getText() != null){
            idAlumno = Integer.parseInt(tIdAlumno.getText());
            ad.borrarAlumno(idAlumno);
        }

    }//GEN-LAST:event_btBorrarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        tIdAlumno.setText("");
        tNombreAlumno.setText("");
        tFecNacAlumno.setText("");
        cbActivo.setSelected(false);
    }//GEN-LAST:event_btLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JCheckBox cbActivo;
    private javax.swing.JComboBox<Especialidad> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tIdEspecialidad;
    private javax.swing.JTextField tNombreEspecialidad;
    private javax.swing.JTextField tNombreEspecialidad1;
    private javax.swing.JTextField tNombreEspecialidad2;
    // End of variables declaration//GEN-END:variables
}
