/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massalud.vista;

import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import massalud.controlador.Conexion;
import massalud.controlador.EspecialidadData;
import massalud.controlador.PrestadorData;
import massalud.modelo.Especialidad;
import massalud.modelo.Prestador;

/**
 *
 * @author tetid
 */
public class VistaAdministrarPrestador extends javax.swing.JInternalFrame {

    private PrestadorData pd;
    private EspecialidadData ed;
    private Conexion conexion;
    private List<Especialidad> listaEspecialidades;
    
    /**
     * Creates new form VistaAdministrarPrestador
     */
    public VistaAdministrarPrestador() {
        initComponents();
        
        try {
            conexion = new Conexion();
            pd = new PrestadorData(conexion);
            ed = new EspecialidadData(conexion);
            
            listaEspecialidades = ed.listarEspecialidades();
            
            cargarEspecialidades();
        } catch (ClassNotFoundException ex) {
            System.out.println("No se pudo crear el PrestadorData");
            Logger.getLogger(VistaAdministrarPrestador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tIdPrestador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNombrePrestador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tApellidoPrestador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tDniPrestador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        cbActivo = new javax.swing.JCheckBox();
        btGuardar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btDesactivar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        btSalir1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Administrar Prestador");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id Prestador:");

        tIdPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdPrestadorActionPerformed(evt);
            }
        });
        tIdPrestador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tIdPrestadorKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        tNombrePrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombrePrestadorActionPerformed(evt);
            }
        });
        tNombrePrestador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombrePrestadorKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");

        tApellidoPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApellidoPrestadorActionPerformed(evt);
            }
        });
        tApellidoPrestador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tApellidoPrestadorKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DNI:");

        tDniPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDniPrestadorActionPerformed(evt);
            }
        });
        tDniPrestador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tDniPrestadorKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Especialidad:");

        cbActivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbActivo.setText("Activo");

        btGuardar.setText("Crear");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btDesactivar.setText("Desactivar/activar");
        btDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesactivarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btSalir1.setText("Salir");
        btSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tDniPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbActivo)
                                                .addGap(114, 114, 114))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(cbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGuardar)
                                .addGap(28, 28, 28)
                                .addComponent(btActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDesactivar)
                                .addGap(30, 30, 30)))
                        .addComponent(btLimpiar)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tApellidoPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tNombrePrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tIdPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSalir1)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIdPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombrePrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tApellidoPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDniPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btActualizar)
                    .addComponent(btDesactivar)
                    .addComponent(btLimpiar))
                .addGap(30, 30, 30)
                .addComponent(btSalir1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        int idPrestador;
        String nombre;
        String apellido;
        int dni;        
        boolean activo;
        Especialidad especialidad;
        
        Prestador p;
        idPrestador = Integer.parseInt(tIdPrestador.getText());
        p = pd.buscarPrestador(idPrestador);
        
        nombre = p.getNombre();
        apellido = p.getApellido();
        dni = p.getDni();
        activo = p.isActivo();
        especialidad = p.getEspecialidad();
        
        tNombrePrestador.setText(nombre);
        tApellidoPrestador.setText(apellido);
        tDniPrestador.setText(dni + "");        
        cbActivo.setSelected(activo);
        
        cbEspecialidad.setSelectedIndex(especialidad.getIdEspecialidad() - 1);
   
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tIdPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdPrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdPrestadorActionPerformed

    private void tIdPrestadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdPrestadorKeyTyped
        char myChar = evt.getKeyChar();

        if(!Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tIdPrestadorKeyTyped

    private void tNombrePrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombrePrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombrePrestadorActionPerformed

    private void tNombrePrestadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombrePrestadorKeyTyped
        char myChar = evt.getKeyChar();

        if(Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tNombrePrestadorKeyTyped

    private void tApellidoPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidoPrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApellidoPrestadorActionPerformed

    private void tApellidoPrestadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tApellidoPrestadorKeyTyped
        char myChar = evt.getKeyChar();

        if(Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tApellidoPrestadorKeyTyped

    private void tDniPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDniPrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDniPrestadorActionPerformed

    private void tDniPrestadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDniPrestadorKeyTyped
        char myChar = evt.getKeyChar();

        if(!Character.isDigit(myChar)){
            evt.consume();
        }
    }//GEN-LAST:event_tDniPrestadorKeyTyped

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed

        int idPrestador;
        String nombre;
        String apellido;
        int dni;        
        boolean activo;
        Especialidad especialidad;
        

        Prestador p;

        nombre = tNombrePrestador.getText();
        apellido = tApellidoPrestador.getText();
        dni = Integer.parseInt(tDniPrestador.getText());
        especialidad = (Especialidad)cbEspecialidad.getSelectedItem();
        activo = cbActivo.isSelected();        
        
        p = new Prestador(nombre, apellido, dni, activo, especialidad);
        pd.agregarPrestador(p);

        tIdPrestador.setText(p.getIdPrestador() + "");
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        int idPrestador;
        String nombre;
        String apellido;
        int dni;        
        boolean activo;
        Especialidad especialidad;

        Prestador p;

        if(tIdPrestador.getText() != null && tNombrePrestador.getText() != null && tApellidoPrestador.getText() != null && tDniPrestador.getText() != null && (tDniPrestador.getText().length() >= 7 && tDniPrestador.getText().length() <= 8)){
            idPrestador = Integer.parseInt(tIdPrestador.getText());
            nombre = tNombrePrestador.getText();
            apellido = tApellidoPrestador.getText();
            dni = Integer.parseInt(tDniPrestador.getText());
            activo = cbActivo.isSelected();
            especialidad = (Especialidad)cbEspecialidad.getSelectedItem();
            

            p = new Prestador(nombre, apellido, dni, activo, especialidad);
            p.setIdPrestador(idPrestador);

            pd.actualizarPrestador(p);
        }

    }//GEN-LAST:event_btActualizarActionPerformed

    private void btDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesactivarActionPerformed
        int idPrestador;
        Prestador p;
        
        if(tIdPrestador.getText() != null){
            idPrestador = Integer.parseInt(tIdPrestador.getText());
            p = pd.buscarPrestador(idPrestador);
            
            if(p.isActivo()){
                cbActivo.setSelected(false);
                p.setActivo(false);
            }else{
                cbActivo.setSelected(true);
                 p.setActivo(true);
            }            
            
            pd.actualizarEstadoPrestador(p);           
            
        }

    }//GEN-LAST:event_btDesactivarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        tIdPrestador.setText("");
        tNombrePrestador.setText("");
        tApellidoPrestador.setText("");
        tDniPrestador.setText("");
        cbActivo.setSelected(false);
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_btSalir1ActionPerformed

    
    public void cargarEspecialidades(){
        for(Especialidad e : listaEspecialidades){
            cbEspecialidad.addItem(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btDesactivar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btSalir1;
    private javax.swing.JCheckBox cbActivo;
    private javax.swing.JComboBox<Especialidad> cbEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tApellidoPrestador;
    private javax.swing.JTextField tDniPrestador;
    private javax.swing.JTextField tIdPrestador;
    private javax.swing.JTextField tNombrePrestador;
    // End of variables declaration//GEN-END:variables
}
